name: Release
on:
  push:
    tags:
    - 'v*'
env:
  GO_VERSION: stable

jobs:
  build_for_linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rows:
        - { goos: linux,   arch: arm64, platform: linux-aarch_64   }
        - { goos: linux,   arch: amd64, platform: linux-x86_64     }
    steps:
    - name: Install build dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y --no-install-recommends \
          build-essential zip
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Build
      shell: bash
      env:
        CGO_ENABLED: 1
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: make release
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-linux-${{ strategy.job-index }}
        path: nostr-relay-linux-*.zip

  build_for_macos:
    name: Build for MacOS
    runs-on: macos-latest
    strategy:
      matrix:
        rows:
        - { goos: darwin,  arch: arm64, platform: osx-aarch_64     }
        - { goos: darwin,  arch: amd64, platform: osx-x86_64       }
    steps:
    - name: Install build dependencies
      run: brew install coreutils zip
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Build
      shell: bash
      env:
        CGO_ENABLED: 1
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: make release
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-darwin-${{ strategy.job-index }}
        path: nostr-relay-darwin-*.zip

  build_for_windows:
    name: Build for Windows
    runs-on: windows-latest
    strategy:
      matrix:
        rows:
        - { goos: windows, arch: arm64, platform: windows-aarch_64 }
        - { goos: windows, arch: amd64, platform: windows-x86_64   }
    steps:
    - name: Install build dependencies
      run: choco install zip mingw
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Build
      shell: bash
      env:
        CGO_ENABLED: 1
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: make release
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-windows-${{ strategy.job-index }}
        path: nostr-relay-windows-*.zip

  release:
    name: Draft Release
    needs:
      - build_for_linux
      - build_for_macos
      - build_for_windows
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: nostr-relay ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          generate_release_notes: true
          files: |
            dist-*/nostr-relay-linux-arm64-*.zip
            dist-*/nostr-relay-linux-amd64-*.zip
            dist-*/nostr-relay-darwin-arm64-*.zip
            dist-*/nostr-relay-darwin-amd64-*.zip
            dist-*/nostr-relay-windows-arm64-*.zip
            dist-*/nostr-relay-windows-amd64-*.zip
